---
title: "Data Manipulation"
output: github_document
---

```{r setup, echo = FALSE, message = FALSE}
library(tidyverse)
```

This document will show how to *manipulate* data.

Import the two datasets that we're going to manipulate

```{r}
litters_df = 
  read_csv("data/FAS_litters.csv", na = c("NA", ",", "."))

litters_df = janitor::clean_names(litters_df)

pups_df = 
  read_csv("data/FAS_pups.csv", na = c("NA", ",", "."))

pups_df = janitor::clean_names(pups_df)
```

## `select`

Use `select()` to select variables

```{r}
select(litters_df, group, litter_number, gd0_weight)
```

```{r}
select(litters_df, group::gd18_weight)
```

```{r}
select(litters_df, -pups_survive)
```

```{r}
select(litters_df, -(group:gd18_weight))
```

```{r}
select(litters_df, starts_with("gd"))
select(litters_df, contains("pups"))
```

```{r}
select(litters_df, GROUP = group)

rename(litters_df, GROUP = group)

select(litters_df, litter_number, gd0_weight, everything())

relocate(litters_df, litter_number, gd0_weight)
```

## `filter`

```{r}
filter(litters_df, gd_of_birth == 20)
```

```{r}
filter(litters_df, pups_born_alive > 8)|>
  relocate(pups_born_alive)
```

```{r}
filter(litters_df, group %in% c("Low7", "Low8")|pups_born_alive == 8) |>
  select(group, pups_born_alive, everything())
```

```{r}
# Drop NA value within selected column
drop_na(litters_df, gd0_weight)
```

```{r}
filter(pups_df, (sex == 2) & (pd_walk <11))
```

## `mutate`

```{r}
mutate(litters_df, wt_gain = gd18_weight - gd0_weight, .before = 1)

mutate(litters_df, sq_pups = pups_born_alive^2, .before = 1) |>
  relocate(pups_born_alive)

mutate(litters_df, group = str_to_lower(group))
```

## `arrange`

```{r}
arrange(litters_df, gd0_weight)

arrange(litters_df, desc(gd0_weight))

# pups_born_alive first, within each value of pups, arrange gd0_weight
arrange(litters_df, pups_born_alive, gd0_weight)|>
  relocate(pups_born_alive, gd0_weight)
```

## Piping

```{r}
# na = c("NA"...) because the import format is chr
litters_df = 
  read_csv("data/FAS_litters.csv", na = c("NA", ".", "")) |>
  janitor::clean_names() |>
  select(-pups_born_alive) |>
  filter(group == "Con7") |>
  mutate(
    wt_gain = gd18_weight - gd0_weight) |>
  lm(wt_gain ~ gd18_weight)

write_csv(litters_df, "data/cleaned_fas_litters.csv")
```

